server:
  servlet:
    context-path: /demo
  port: 8001
spring:
  rabbitmq:
    addresses:
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
    publisher-confirm-type: simple
    publisher-returns: true
    template:
      mandatory: true
    listener:
        simple:
          auto-startup: false
elastic-job:
  zookeeper:
    serverLists: localhost:2181
    namespace: elastic-job
